### ISSUE TITLE
I want to give a talk!

### ISSUE THREAD

**Issue by belcherj** [TacoJS/tacojs.github.io#1]
Fetch API?  Spread Operator?  Webpack? Stylelint?

**Comment by belcherj** [comment]
Unfortunately I'm out of town 14 July.  I want to speak at the next tacoJS.

**Comment by pixelyunicorn** [comment]
Feel free to submit as many issues as you want over at https://github.com/TacoJS/talks/issues/new! 

If you haven't yet, take a look at the speaker FAQ: http://tacojs.rocks/speak 😄
